version: '2.1'

networks:
  bridge: {}

services:
  publisher:
    extends:
      file: ./python/pika.yml
      service: pika
    entrypoint: ./publisher
    links:
      - broker
  consumer:
    extends:
      file: ./python/pika.yml
      service: pika
    entrypoint: ./consumer
    links:
      - broker
  timestamper:
    extends:
      file: ./python/pika.yml
      service: pika
    entrypoint: ./timestamper
    links:
      - broker
